### PR TITLE
Windows support

### LINKED ISSUE #34: build error: program not found
Hello. I tried to run the following source code on Windows 10 and the build failed. I am seeking assistance in resolving this issue.

## Code
```rust
use pg_query;

fn main() {
    let result = pg_query::parse("SELECT * FROM contacts");
    assert!(result.is_ok());
}
```

## Error message
The project is located at `E:\pg-query-test`.

```
error: failed to run custom build command for `pg_query v0.8.2`

Caused by:
  process didn't exit successfully: `E:\pg-query-test\target\debug\build\pg_query-4000e504282b2f84\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-changed=.\libpg_query\Makefile
  cargo:rustc-link-search=native=E:\pg-query-test\target\debug\build\pg_query-b2e470b4f0427967\out
  cargo:rustc-link-lib=static=pg_query

  --- stderr
  Error: Error { kind: NotFound, message: "program not found" }
```

## Environment
OS: Windows 10
pg_query: 0.8.2
cargo: 1.75.0-nightly
cmake: 3.28.1

### PR DESCRIPTION
**Pull request by lfittl**
Note that this also removes our use of the `Makefile` in `build.rs`, and instead uses the `cc` crate to build libpg_query directly. This matches what we do in other libraries (pg_query in Ruby, pg_query_go).

Depends on https://github.com/pganalyze/libpg_query/pull/233

Fixes #34

### CODE REVIEW

File: build.rs [hunk 1]
```diff
@@ -35,19 +35,29 @@ fn main() -> Result<(), Box<dyn std::error::Error>> {
...
+        .file(out_dir.join("vendor/xxhash/xxhash.c"))
+        .file(out_dir.join("protobuf/pg_query.pb-c.c"))
+        .include(out_dir.join("."))
+        .include(out_dir.join("./vendor"))
+        .include(out_dir.join("./src/postgres/include"))
+        .include(out_dir.join("./src/include"));
+    if env::var("PROFILE").unwrap() == "debug" || env::var("DEBUG").unwrap() == "1" {
+        build.debug(true);
+        build.opt_level(0);
+        build.define("USE_ASSERT_CHECKING", None);
```
Comment (msepga) [inline build.rs:52]: We don't actually have to manually call `debug` or `opt_level` here - these are automatically set by `cc` based on the values of `OPT_LEVEL` and `DEBUG`, which are [set automatically](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts) by cargo when running a build script.

We can however still rely on `DEBUG` here for `USE_ASSERT_CHECKING`

File: build.rs [hunk 2]
```diff
@@ -35,19 +35,29 @@ fn main() -> Result<(), Box<dyn std::error::Error>> {
...
+    build
+        .files(glob(out_dir.join("src/*.c").to_str().unwrap()).unwrap().map(|p| p.unwrap()))
+        .files(glob(out_dir.join("src/postgres/*.c").to_str().unwrap()).unwrap().map(|p| p.unwrap()))
+        .file(out_dir.join("vendor/protobuf-c/protobuf-c.c"))
+        .file(out_dir.join("vendor/xxhash/xxhash.c"))
+        .file(out_dir.join("protobuf/pg_query.pb-c.c"))
+        .include(out_dir.join("."))
+        .include(out_dir.join("./vendor"))
+        .include(out_dir.join("./src/postgres/include"))
+        .include(out_dir.join("./src/include"));
```
Comment (msepga) [inline build.rs:48]: Do we want to suppress the C warnings here, using [`.warnings(false)`](https://docs.rs/cc/latest/cc/struct.Build.html#method.warnings)? These might not be as relevant to the `pg_query.rs` project, compared to working directly in the `libpg_query` repo.

**Review by msepga — APPROVED** [review]
Left 2 nits but otherwise LGTM. I can confirm tests are passing here 👍
